name = "gleam_community_ansi"
version = "1.4.3"
licences = ["Apache-2.0"]
description = "ANSI colours, formatting, and control codes"
repository = { type = "github", user = "gleam-community", repo = "ansi" }
gleam = ">= 0.33.0"

[dependencies]
gleam_stdlib = "~> 0.34"
gleam_community_colour = ">= 1.3.0 and < 3.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
